app/models.py
from . import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True)
    email = db.Column(db.String(255), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    password_hash = db.Column(db.String(255))

    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'User {self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    users = db.relationship('User', backref='role', lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'


class Pitch(db.Model):
    __tablename__ = 'goal_pitch'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    body = db.Column(db.String)

    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    category_id = db.Column(db.Integer, db.ForeignKey("category.id"))

    comments = db.relationship(
        'Comment', backref="main_pitch", cascade="all, delete-orphan", lazy="dynamic")

    def __repr__(self):
        return f'User {self.title}'


class Category(db.Model):
    __tablename__ = 'category'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))

    pitch = db.relationship('Pitch', backref='parent_category', lazy='dynamic')

    def __repr__(self):
        return f'Category {self.name}'


class Comment(db.Model):
    __tablename__ = 'comment'

    id = db.Column(db.Integer, primary_key=True)
    author = db.Column(db.String(255))
    comment = db.Column(db.String)

    goal_pitch_id = db.Column(db.Integer, db.ForeignKey("goal_pitch.id"))

    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, ValidationError, StringField
from wtforms.validators import Required, Email, DataRequired
from ..models import User


class GoalForm(FlaskForm):
    title = StringField('Pitch Category Title', validators=[DataRequired()])
    body = TextAreaField('Enter your Pitch here', validators=[DataRequired()])
    submit = SubmitField('Submit')

    '''
    crate the inputs for comments form with vite options
    '''


class CommentForm(FlaskForm):
    comment = TextAreaField('Write a comment here',
                            validators=[DataRequired()])

    submit = SubmitField('Submit')

    '''
    crate the inputs for comments form with vote option
    '''


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import DevConfig
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_mail import Mail
from flask_uploads import UploadSet, configure_uploads, IMAGES
from config import config_options
from flask_sqlalchemy import SQLAlchemy

bootstrap = Bootstrap()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

photos = UploadSet('photos', IMAGES)

mail = Mail()


def create_app(config_name):

    app = Flask(__name__)

    # # Creating the app configurations
    app.config.from_object(config_options[config_name])
    app.config['SECRET_KEY'] = 'any secret string'

    configure_uploads(app, photos)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, error, forms

app/main/views.py
from flask import render_template, request, redirect, url_for, abort, flash
from .forms import UpdateProfile, GoalForm, CommentForm
from ..models import User, Category, Pitch, Comment
from .. import db, photos
from flask_login import login_required, current_user

from . import main

# Views


@main.route('/')
@login_required
def index():
    '''
    View root page function that returns the index page and its data
    '''
    title = 'Goals Pitching!!'
    message = "Welcome to Goals pitching. Post your pitches and view others. Don't forget to comment and vote!! Enjoy!!"
    return render_template('index.html', message=message, title=title)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username=uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user)


@main.route('/pitch//new', methods=['GET', 'POST'])
@login_required
def new_pitch():
    '''
       view function that defines the routes decorater for the pitch
        '''

    form = GoalForm()
    if form.validate_on_submit():
        pitch = Pitch(title=form.title.data,
                      body=form.body.data, user_id=current_user.id)
        db.session.add(pitch)
        db.session.commit()
        flash('Your pitch has been created succesfully')
        return redirect(url_for('main.new_pitch'))

    pitch = Pitch.query.all()

    return render_template('goal.html', form=form, pitch_list=[pitch])


@main.route('/comment/new', methods=['GET', 'POST'])
@login_required
def new_comment():
    '''
      view  function that defines the routes decorater for the comments
        '''

    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        comment = Comment(comment=comment_form.comment.data)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been posted succesfully')
        return redirect(url_for('main.new_comment'))
    comment = Comment.query.all()
    return render_template('comment.html', comment_form=comment_form, comment_list=comment)


@main.route('/user/<uname>/update', methods=['GET', 'POST'])
def update_profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname=user.username))

    return render_template('profile/update.html', form=form)


@main.route('/user/<uname>/update/pic', methods=['POST'])
def update_pic(uname):
    user = User.query.filter_by(username=uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        # user_photo = PhotoProfile(pic_path=path, user=user)
        # db.session.commit()
    return redirect(url_for('main.profile', uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/category.html
{% extends 'bootstrap/base.html'%}
<!-- {% import 'bootstrap/wtf.html' as wtf%} -->
{% block navbar %}
{% include 'navbar.html'%}
{% endblock %}
{% block content %}
<h2 class="text-center">General pitches</h2>
<div class="col-md-2"> </div>
<div class="col-md-8">


</div>
{% endblock %}

app/templates/comment.html
{% extends 'bootstrap/base.html'%}
<!-- {% import 'bootstrap/wtf.html' as wtf%} -->

{% import 'macros.html' as macro %}

{% block navbar %}
{% include 'navbar.html'%}
{% endblock %}

<!-- Styles block -->
{% block styles %}{{ super() }} {% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
        {{wtf.quick_form(comment_form)}}
    </div>
    <div class="col-md-2">
    </div>
</div>
<div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-6">
        {{macro.displayCommentList(comment_list)}}
    </div>
    <div class="col-md-2">
    </div>
</div>
{% endblock content%}

app/templates/goal.html
{% extends 'base.html' %}
<!-- {% import 'bootstrap/wtf.html' as wtf%} -->
{% import 'macros.html' as macro %}
{% block navbar %}
{% include 'navbar.html'%}
{% endblock %}
{% block content %}

<div class="container-fluid">
    <h1 class="text-center">WRITE YOUR PITCHES BELOW HERE!</h1>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.body.label(class="form-control-label") }}
                    {% if form.body.errors %}
                    {{ form.body(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.body(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>

    </div>

</div>

<hr>
<!-- Content block -->
<div class="container-fluid mt-3">
    <div class="row">
        {{macro.displayPitchList(goal_pitch_list)}}

    </div>
</div>








{% endblock content %}

app/templates/index.html
{% extends 'base.html'%}
<!-- {% import 'bootstrap/wtf.html' as wtf%} -->
{% import 'macros.html' as macro %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
{% endblock %}


{% block content %}
<div class="container-fluid">
    <h1 class="text-center">PRESENT YOUR PITCH TODAY</h1>
    <div class="row">
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="container">
        <div class="panel panel-default panel-heading"><a href="/pitch//new">KOT</a></div>
        <div class="panel panel-default panel-heading"><a href="/pitch//new">Pick up</a></div>
        <div class="panel panel-default panel-heading"><a href="/pitch//new">Programming Jokes</a></div>
        <div class="panel panel-default panel-heading"><a href='/category/interview'>Memes</a></div>
    </div>
</div>
{{macro.displayPitchList(goal_pitch_list)}}

{% endblock%}

app/templates/login.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"> </div>
        <div class="col-md-8">
            <!--Flash message -->
            {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
            <!-- Login form -->
            {{wtf.quick_form(login_form)}}
            <p> Don't have an account? <a href="{{url_for('auth.register')}}">Sign up here</a></p>
        </div>
        <div clas="col-md-2"> </div>
    </div>
</div>

{% endblock%}

app/templates/macros.html
{% macro displayPitchList(pitch_list) %}
{% for goal_pitch in pitch_list %}
<div class="col-md-1">
</div>
<div class="col-md-10">
    <div class="card m-7">
        <div class="card-header">
            <h3 class="card-title">{{goal_pitch.title}}</h3>
        </div>
        <div class="card-body">
            <p class="card-text">{{goal_pitch.body}}</p>
        </div>
        <hr>
        <div class="card-footer">
            <a href="{{ url_for('main.new_comment') }}" class="btn btn-success btn-sm">Comment</a>
            <a href="{{ url_for('main.new_comment') }}" class="btn btn-success btn-sm">Vote</a>
        </div>
    </div>
</div>
<div class="col-md-1">
</div>
{% endfor %}
{% endmacro %}
{% macro displayCommentList(comment_list)%}
{% for review in comment_list %}
<div class="col-md-3">
</div>
<div class="col-md-6">
    <p>{{review.comment}}</p>
</div>
<div class="col-md-3">
</div>
</div>

{% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Goals pitching </a>

            <ul class="nav navbar-nav navbar-right">

                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
        </div>

    </div>
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
{% if user == current_user %}
<a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>

        {% if user == current_user %}
        <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
        {% endif %}
        <!--Display profile photo-->
        <div class="col-md-4">

            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}
            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}